# Use the official Tomcat image
FROM tomcat:10-jdk17

# Remove default Tomcat apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy your WAR file into the Tomcat webapps folder
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war

# Expose the port
EXPOSE 8080

CMD ["catalina.sh", "run"]